### ISSUE TITLE
Add extension option to supply additional parameters

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#108]
E.g. `-Xmx` and so forth.

**Comment by manoj2601** [comment]
Can you provide some more details about these?

**Comment by magnus-madsen** [comment]
If you go to extension settings:

![image](https://user-images.githubusercontent.com/2287953/124084677-88f59700-da4f-11eb-9037-03ad0888a81d.png)

I would like to be able to have a text box where you can enter extra arguments for the JVM

**Comment by manoj2601** [comment]
![Screenshot from 2021-07-05 16-36-23](https://user-images.githubusercontent.com/45541010/124462298-34378080-ddaf-11eb-9e60-4c394a3adcf8.png)

This kind of box seems good.
