### ISSUE TITLE
Save dirty buffers on run?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#111]
When the user clicks run (or similar) we should check if there are UNSAVED files in the workspace.

If so, we should show a dialog asking the user if he or she wants to save the files before running the command.

**Comment by manoj2601** [comment]
We can implement this in the following way:
* If the user clicks on `run` (or similar), A dialogue box with two buttons: `run without saving` and `check unsaved files` appears.
  
![Screenshot from 2021-07-08 12-58-29](https://user-images.githubusercontent.com/45541010/124881485-03dd2580-dfed-11eb-8cb4-ba51cac13f3d.png)
    1. If the user clicks on `run without saving`, it will run normally without saving anything.
    2. If the user clicks on `check unsaved files`, a list will appear to pick files that need to be saved. User can pick the files (including `untitled` files) which he/she wants to save.
    ![Screenshot from 2021-07-08 12-58-41](https://user-images.githubusercontent.com/45541010/124881496-06d81600-dfed-11eb-8ca5-f61c6f3b0707.png)
    3. If the user selects any `untitled` file, a save dialogue box will open to save the file on a location.

**Comment by magnus-madsen** [comment]
I am OK with the first dialog box, but I don't think the user should have to select the files that should be saved.

Is it not possible to ask VSCode to save all modified files?

**Comment by manoj2601** [comment]
Yes, it is possible.
But what if there are some `untitled` files?

**Comment by magnus-madsen** [comment]
> But what if there are some `untitled` files? By `untitled` files, I mean to say about the files that are created in vs code workspace but never saved.

Its a good point. I think we just ignore those. Its not perfect, but I don't know what else we can really do.
