### ISSUE TITLE
Add Commands: pkg/*

### ISSUE THREAD

**Issue by plougsgaard** [flix/vscode-flix#12]
Add pkg commands to the command palette.

- [ ] `pkg/benchmark`
- [ ] `pkg/build`
- [ ] `pkg/buildDoc`
- [ ] `pkg/buildJar`
- [ ] `pkg/buildPkg`
- [ ] `pkg/init`
- [ ] `pkg/test`

All commands should be prefixed with `Flix:`.

**Comment by magnus-madsen** [comment]
Note these commands don't actually do anything yet on the server-side.
