### ISSUE TITLE
Add Semantic Token Support

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#122]
See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens

**Comment by jhckragh** [comment]
I've been trying to get this to work, but without success. I'll share what I've learnt so far. Maybe it can help others or provide some amusement. 😉

1. Start by enabling semantic highlighting by adding the following to [package.json](https://github.com/flix/vscode-flix/blob/master/package.json):

```javascript
"configurationDefaults": {
    "[flix]": {
        "editor.semanticHighlighting.enabled": true
    }
},
```

Without this, requests for semantic highlighting won't trigger automatically. The Dark+ theme has this enabled, but FlixifyDark doesn't. Took me quite some time to figure this out! 😵

2. Add the capability to the language server, e.g. by adding the following to the `capabilities` object in [handlers.ts](https://github.com/flix/vscode-flix/blob/master/server/src/handlers/handlers.ts):

```javascript
semanticTokensProvider: {
    legend: {
        tokenTypes: ["namespace"],
        tokenModifiers: ["declaration"]
    },
    full: true
}
```

Of course, the legend should be richer than this, but that can come later.

3. If you start the extension now, you should see an error message like this:

```
[Error - HH.MM.SS] Request textDocument/semanticTokens/full failed.
  Message: Unhandled method textDocument/semanticTokens/full
```

This indicates that semantic token requests are now being triggered (but not yet handled by the server).

4. One way of getting the server to handle the new request type is to add the following to [server.ts](https://github.com/flix/vscode-flix/blob/master/server/src/server.ts):

```javascript
connection.onRequest(SemanticTokensRequest.method, handlers.handleSemanticTokens)
```

and then introduce a function `handleSemanticTokens` in [handlers.ts](https://github.com/flix/vscode-flix/blob/master/server/src/handlers/handlers.ts). I've tried with the following:

```javascript
export function handleSemanticTokens (params: SemanticTokensDeltaParams) {
    const job: jobs.Job = {
        request: jobs.Request.lspSemanticTokens,
        uri: params.textDocument.uri
    }
    queue.enqueue(job)
}
```

where `lspSemanticTokens` will need to be added to the `Request` enum. (Note that some imports will also need to be added to make the above code compile - just click on the red squiggly lines and then use the code actions to add the necessary imports.)

5. If you start the extension now, you should see an error message like this:

```
[2021-09-05 HH:MM:SS] [/127.0.0.1:63336]: Unsupported request: 'JString(lsp/semanticTokens)'.
```

This error message comes from `flix.jar`; so the requests for semantic tokens are getting passed successfully to the real Flix LSP!

6. The next step is probably to handle the `lsp/semanticTokens` request in the Flix LSP.

I've tried to handle the request in a similar fashion to the other requests, starting with a stub response in `LanguageServer.scala` looking like this:

```scala
case Request.SemanticTokens(id, uri) =>
    ("id" -> id) ~ ("status" -> "success") ~ ("result" -> ("data" -> JArray(List(0, 10, 3, 0, 0))))
```

It's meant to mark the identifier in the following code:

```flix
namespace Bla {}
```

The hardcoded response causes the error message to disappear. And by using the debugger in VS Code I can see that the response gets sent back successfully to the extension.

7. But at this point I get stuck. I can't figure out what the extension does with the response it receives. It emits it on some `EventEmitter`, but I don't know what happens then.

It might be necessary to add something like the following to the client:

```javascript
client.registerFeature(new SemanticTokensFeature(client));
```

I've tried this, but I haven't observed any difference.

When I get more time, I might try something like the approach taken in OmniSharp: https://github.com/OmniSharp/omnisharp-vscode/blob/d1785942e51f3afee1d8e62b406ee46b35168c63/src/features/semanticTokensProvider.ts

**Comment by magnus-madsen** [comment]
@jhckragh You are on the right track, but some things are enabled wrong.

Take a look at the recent PR: https://github.com/flix/vscode-flix/pull/144/files to see how another feature was enabled.

**Comment by magnus-madsen** [comment]
And also: https://github.com/flix/flix/pull/2289

**Comment by jhckragh** [comment]
Thanks for taking a look! 🙂 I've already looked at the implementation of the other features  (including the nice recent work on documentSymbol). But it seems to me that the same approach can't be used directly to handle semantic tokens because:

- There's no `onSemanticTokens` method on the `connection` object.
- The semantic tokens request is not associated with a position, so it seems strange to attach a positional handler.

**Comment by magnus-madsen** [comment]
> Thanks for taking a look! 🙂 I've already looked at the implementation of the other features (including the nice recent work on documentSymbol). But it seems to me that the same approach can't be used directly to handle semantic tokens because:
> 
> * There's no `onSemanticTokens` method on the `connection` object.
> * The semantic tokens request is not associated with a position, so it seems strange to attach a positional handler.

Hmm. I don't know the answer. Semantic tokens appeared in 3.16- the latest LSP. Could it be that the template we used for the VSCode part is a bit oudated?

Would it make sense to try to start the implementation on the Flix compiler see? The spec should tell us the necessary data structures?

**Comment by magnus-madsen** [comment]
Based on your description, it seems just must be *very close* to something that works.

**Comment by magnus-madsen** [comment]
Since you have almost the entire round trip.

**Comment by jhckragh** [comment]
Thanks for the feedback, Magnus! It would indeed make sense to start the implementation on the Flix compiler. But it would be nice to be able to see the results in the extension while one is working on that. Fortunately I think I've managed to figure it out now!

Replace the two code snippets in step 4 above with

```javascript
connection.languages.semanticTokens.on(handlers.handleSemanticTokens)
```

respectively

```javascript
export const handleSemanticTokens = makePositionalHandler(jobs.Request.lspSemanticTokens)
```

(I was afraid that `makePositionalHandler` wouldn't work without a position, but I see now that the position is actually optional.) 🙏

Here's how it looks with the scope inspector activated:

![flix-st-example](https://user-images.githubusercontent.com/129259/132241787-8ae489ee-eb25-451f-8f5b-7786cb30e8c0.png)

Woo! 🥳

By the way, I figured out the right way of registering the handler by looking at this file: https://github.com/microsoft/vscode-languageserver-node/blob/301224db3cd88571d51971ac512b3031b91fb07b/testbed/server/src/server.ts

**Comment by magnus-madsen** [comment]
@jhckragh Did we manage to add semanticTokens to the VSCode part? Or is that not done yet?

No rush, but do you have future plans to continue working on the SemanticToken part in the Flix compiler? :)

**Comment by magnus-madsen** [comment]
> 
> 
> Follow-up: I've found a bug in my code! 😧 Maybe you have an idea for how to proceed? I can illustrate it with the following example:
> 
> ```
> def _f(xs: List[String]): Unit & Impure =
>     let _ys = xs;
>     let p = println;
>     let g = (x -> x);
>     123 |> g |> p;
>     ()
> ```

In the above code I would say that `xs`, `_ys`, `p`, `g`, and `x` are all local variables (`Expression.Var`). In addition, `println` and `|>` are references to function definitions `Expression.Def`). I think that is what should be reported to vscode.

Does that help?

**Comment by jhckragh** [comment]
Thanks for the input! I've handled `Def`s separately; that part of my code seems to be okay. As for the right highlighting of `p`: Here I was just trying to follow what the builtin language server for JavaScript does in VSCode:

![vscodejs](https://user-images.githubusercontent.com/129259/137626368-c408e45a-aa5d-4f8a-baa5-b423d91f64b1.png)

Here both `h` and `g` are classified as function tokens.

**Comment by jhckragh** [comment]
> 
> 
> Did you want to make a PR that adds semantic token support to `flix/vscode`? Then it would be easy for me to test also :)

Done! Sorry for the delay. My original intention was to wait with it until the language server could actually provide some interesting tokens. But I've now made a PR for it. ☺️

**Comment by jhckragh** [comment]
By the way, maybe the token classification that I proposed for the above example could be achieved by looking at the ` Type.Apply(tpe1, tpe2, loc)` and checking whether the `tpe1` is a type constructor? That could be used to check for e.g. `List[String]`. I don't know if it's too much of a hack/workaround though.

**Comment by magnus-madsen** [comment]
> 
> 
> By the way, maybe the token classification that I proposed for the above example could be achieved by looking at the `Type.Apply(tpe1, tpe2, loc)` and checking whether the `tpe1` is a type constructor? That could be used to check for e.g. `List[String]`. I don't know if it's too much of a hack/workaround though.

Yes, it would be possible, but I am not sure whether it is a good idea. I don't understand why does VSCode do it for JavaScript? A variable should be a variable, no?

**Comment by jhckragh** [comment]
> Yes, it would be possible, but I am not sure whether it is a good idea. I don't understand why does VSCode do it for JavaScript? A variable should be a variable, no?

Maybe they choose this behavior to "give equal treatment to" the different styles that can be used for declarations?

```javascript
// Style 1
function g(x) {
    return x;
}

// Style 2
const g = x => x;
```

I kind of like the VScode behavior because it will make each piece of a Flix pipeline highlight as a function (except possibly the first one, depending on its type):

```
123 |>
double |> // function
square |> // function
println   // function
```

But you're the boss. If you don't like it, I can just leave it out (that also makes the implementation easier). ☺️

**Comment by magnus-madsen** [comment]
We could try it out and see how it is?

**Comment by magnus-madsen** [comment]
Looking at the token types, I think we should support most of them:

- [X] type = 'type',
- [ ] class = 'class',
- [X] enum = 'enum',
- [X] interface = 'interface' // I would use this for our type classes,
- [ ] struct = 'struct' // Maybe can be used for records?,
- [X] typeParameter = 'typeParameter',
- [X] parameter = 'parameter',
- [X] variable = 'variable',
- [ ] property = 'property',
- [X] enumMember = 'enumMember' // corresponds to case,
- [ ] event = 'event' // maybe could be used for channels?,
- [ ] function = 'function',
- [ ] method = 'method' // not sure whether to use function or method for our defs,
- [ ] macro = 'macro',
- [ ] keyword = 'keyword' // AST lacks this information, but I think that part could be kept in the theme,
- [ ] modifier = 'modifier' // same as above,
- [ ] comment = 'comment' // same as above,
- [X] string = 'string' // I think we could use this one. Might work better for interpolated strings,
- [X] number = 'number',
- [ ] regexp = 'regexp',
- [ ] operator = 'operator' // not sure

In general, I would prefer to use sematic tokens for most things, except maybe keywords and modifiers.

**Comment by magnus-madsen** [comment]
I am closing this as solved. We can open individual tickets for the remaining items.
