### ISSUE TITLE
Add exhaustive case generation

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#131]
Would be nice to have something like

```scala
enum E {
  case C1(abc)
  case C2(def)
  case C3(ghi)
}

def f(e: E): Bool = match e {
  <press tab or something>
  <generates:
  case C1(abc) => ???
  case C2(def) => ???
  case C3(ghi) => ???
  >
}
```

**Comment by magnus-madsen** [comment]
Difficult because we cannot parse `def f(e: E): Bool = match e {` but we must know the type of `e`.

**Comment by magnus-madsen** [comment]
If we lookup what functions we are inside, we could find the local variables, then find their types, and then add completions like:

`match x { ... }`
`match y {...}`

Its not exactly the same, because here you have to choose the variable you want to match on.

**Comment by magnus-madsen** [comment]
Fixed in master.
