### ISSUE TITLE
Feature request: Highlight failed tests

### ISSUE THREAD

**Issue by jaschdoc** [flix/vscode-flix#143]
Currently test results are shown as a long list and if a failed test is at the top of that list, I'm required to scroll to the top to check it manually. This manual step in automated testing is obviously error prone and failed tests could easily get overlooked. I suggest either printing a summary in the bottom of the output message or collecting failed tests and appending those to the bottom of the message or some other solution I haven't thought of. Either way, it should be easily visible that something is broken when tests fails.

Top of output message
![Screenshot from 2021-09-01 17-22-19](https://user-images.githubusercontent.com/60233376/131698687-d57b82fa-d527-421d-8ea2-85b479bdb240.png)
...
Bottom of output message
![Screenshot from 2021-09-01 17-27-09](https://user-images.githubusercontent.com/60233376/131699577-34bcdea9-974b-4c75-a89d-96de60849173.png)

**Comment by magnus-madsen** [comment]
Agreed!

**Comment by magnus-madsen** [comment]
Fixed in master. Give it a spin!
