### ISSUE TITLE
Instance code generation uses and/or/not type symbols instead of text

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#145]
In a file with this class:

```
lawless class C[a] {
    pub def f(g: a -> a & ef1, h: a -> a & ef2): a & ef1 and ef2
}
```

This is generated when I try to create an instance.
```
instance C[a] {

  pub def f(g: a -> a & ef1, h: a -> a & ef2): a & ef1 ∧ ef2 = ???

}
```

The `∧` symbol is invalid syntax.

**Comment by magnus-madsen** [comment]
You mean that the formatting is broken?

**Comment by magnus-madsen** [comment]
This problem is really in the compiler, right?

**Comment by mlutze** [comment]
Yes, the formatting produced is "display" formatting, but it's not suitable for code generation.



> This problem is really in the compiler, right?

I would guess so.

**Comment by magnus-madsen** [comment]
I mean ∧ should just be changed to and.

**Comment by mlutze** [comment]
> I mean ∧ should just be changed to and.

Yes, that's the simplest solution

**Comment by magnus-madsen** [comment]
I think this has been fixed.
