### ISSUE TITLE
Show changelog on compiler update

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#146]
Or link to it or something, so people can get excited about new features

**Comment by magnus-madsen** [comment]
@nicdard Perhaps you would be interested in this? It seems straightforward, at least to someone who knows JavaScript :)

**Comment by nicdard** [comment]
Sure! Unfortunately I have still to deal with some project/homework at uni, I have to hand out them shortly. As soon as I am ready I will start again to look at issues and PRs that are still open :)
