### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by nicdard** [flix/vscode-flix#149]
I have taken a look at the code while contributing and I think some part are really hard to be modified/understood at first glance.

I would like to propose some refactoring, starting by cleaning up type information which are often missing (extensive use of `any` type) and rewrite some code which seems to rely on poor typing to work thus being hard to navigate and understood.

If the maintainers are ok and happy with this I will try to work by submitting small as possible changes at a time, although it may be difficult.

Here is a first short list of general things that I think are missing at first glance, feel free to suggests addition/deletion:
- [ ] provide better typing
- [ ] configure stricter linter
- [ ] tests

**Comment by magnus-madsen** [comment]
I don't know specifically what you have in mind, but if you propose some small PRs I would be happy to look at them!
