### ISSUE TITLE
Ensure that VSCode works without internet

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#151]

**Comment by magnus-madsen** [comment]
@nicdard Perhaps you could lend a hand? :) 

I believe the problem is that when the extension starts it checks for a new version of Flix, but if the internet is not available it may hang. Could that be the case?

**Comment by nicdard** [comment]
Sure :)

I can check for it as soon as I finish some university assignments that I have during those days

**Comment by magnus-madsen** [comment]
Thanks! That would be great. No rush :)

**Comment by nicdard** [comment]
Sorry for taking so long, I had a series of issues apart from university that took away all the time from me. 

Regarding the issue, @magnus-madsen I can confirm the error derives from the extension try to check if there is an updated version. if I am in the editor without internet and I try to restart the compiler the error shows up:
![Screenshot from 2021-12-16 22-30-40](https://user-images.githubusercontent.com/55001950/146452280-ce843a0b-d949-4e38-947d-f04d24dead5d.png)

**Comment by magnus-madsen** [comment]
I am not sure it relates to the JAR. If I have no internet it does not work, so I think you can test by disconnecting the net.

**Comment by nicdard** [comment]
I have tried already but if I have a jar the error isn't triggered

**Comment by magnus-madsen** [comment]
> I have tried already but if I have a jar the error isn't triggered

Interesting. What happens if you open VSCode, play around a bit, go to standby, resume and then try hover? For me that breaks things. Maybe these are separate issues?

**Comment by nicdard** [comment]
> > I have tried already but if I have a jar the error isn't triggered
> 
> Interesting. What happens if you open VSCode, play around a bit, go to standby, resume and then try hover? For me that breaks things. Maybe these are separate issues?

When hovering I see a `Loading...` but nothing happens. Also if I try to restart the extension, the job timeouts.

**Comment by magnus-madsen** [comment]
> > > I have tried already but if I have a jar the error isn't triggered
> > 
> > 
> > Interesting. What happens if you open VSCode, play around a bit, go to standby, resume and then try hover? For me that breaks things. Maybe these are separate issues?
> 
> When hovering I see `Loading...` but nothing happens. Also if I try to restart the extension, the job timeouts.

Yes. That's the bug.
