### ISSUE TITLE
Revisit keyword classification

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#168]
The classification of keywords seems unclear at times.

For example:
![Screenshot from 2021-11-15 16-53-10](https://user-images.githubusercontent.com/19153692/141812619-ae86b77d-697f-46b2-941a-cf46175ea8ab.png)
`pub` is a modifier, and `opaque type` in my view is a two-word declaration keyword. But `opaque` gets the modifier formatting, while `pub` gets the declaration keyword formatting.

**Comment by magnus-madsen** [comment]
@jhckragh Could you do your debugging magic again? :)

**Comment by jhckragh** [comment]
Here's the semantic token response provided by the Flix language server:

```
{'id': '3', 'status': 'success', 'result': {'data': [0, 16, 2, 1, 0, 0, 5, 3, 10, 0]}}
```

This translates to:

```
[0:16] 'OT' (ENUM)
[0:21] 'Int' (TYPE)
```

So the classification of `pub`, `opaque` and `type` comes from the VSCode grammar file (lines 92 and 148). 🙂

**Comment by jhckragh** [comment]
If you'd like, I can update the grammar file according to the suggestions from @mlutze? 🙂

**Comment by magnus-madsen** [comment]
So whats the actual problem? That they belong to the wrong category or that the theme treats them weirdly or what?

**Comment by jhckragh** [comment]
They belong to the wrong category in the grammar file:

* `pub` is set as a declaration keyword instead of a modifier.
* `opaque` is set as a modifier.
* `type` is a keyword by itself (a declaration keyword).

**Comment by magnus-madsen** [comment]
OK, so the solution is to make pub a modifier?

**Comment by jhckragh** [comment]
I suggest we make `pub` a modifier and remove `type` as keyword and replace it with `type alias` and `opaque type` (both as declaration keywords). What do you think? 🙂

**Comment by mlutze** [comment]
> I suggest we make `pub` a modifier and remove `type` as keyword and replace it with `type alias` and `opaque type` (both as declaration keywords). What do you think? 🙂

I think this is the right solution. We should be sure that we can support arbitrary whitespace between the keywords though.

While we're here, are there any other tokens that are miscategorized?

**Comment by mlutze** [comment]
After looking at the grammar file, I don't see any other misclassifications.

**Comment by jhckragh** [comment]
Question: As you point out @mlutze, arbitrary whitespace (including comments) can occur between the words in `type alias` and `opaque type`. This can be achieved through the begin/end mechanism in the grammar file, by using e.g. `"\\b(type)\\b"` as the begin pattern and `"\\b(alias)\\b"` as the end pattern. The result can be seen here:

![0](https://user-images.githubusercontent.com/129259/142024528-d4542c38-2225-4327-8e5d-db74cb6dbb16.png)

But with this approach we get the same highlighting effect as with strings: When you type in `"`, then any code that comes after the cursor will be miscolored until the matching `"` is typed in. (In our case it would be e.g. `opaque` having to be matched by `type`). The effect can be seen here:

![1](https://user-images.githubusercontent.com/129259/142025134-47a29c27-137b-4622-8e37-46a130cddb96.png)

Alternatively we could use a single-line pattern like `"\\b(type[ \t]+alias)\\b"`, but then a comment placed in between the two words would cause the highlighting to fail.

Which approach do you guys prefer? Or do you have other ideas for tackling it? 🙂

**Comment by magnus-madsen** [comment]
I don't think we should allow more than just a space between `type` and `alias`.

**Comment by magnus-madsen** [comment]
Why can't both `type` and `alias` be two keywords?

**Comment by jhckragh** [comment]
> Why can't both `type` and `alias` be two keywords?

That would indeed be the simplest solution here. 🙂 I guess the counterargument is that neither word is syntactically valid on its own; they must occur in combination.

**Comment by magnus-madsen** [comment]
> 
> 
> > Why can't both `type` and `alias` be two keywords?
> 
> That would indeed be the simplest solution here. 🙂 I guess the counterargument is that neither word is syntactically valid on its own; they must occur in combination.

Aah who cares. The compiler will check that. I would just make them keywords of the appropriate kind.

**Comment by magnus-madsen** [comment]
Fixed in master. Thanks @jhckragh !
