### ISSUE TITLE
Wrong type hovers for LHS of local variable declarations

### ISSUE THREAD

**Issue by jhckragh** [flix/vscode-flix#172]
(Tested with `v0.53.0` of the extension and nightly `flix-2021-11-19.jar`.)

![flix-hover-localdecl](https://user-images.githubusercontent.com/129259/142738229-ba188143-f3a0-49b0-9635-e605031b8c4b.png)

As illustrated: When one hovers over an identifier occurring on the left-hand side in a `let`, the type shown seems to be the return type of the enclosing `def`, not the type inferred for the variable.

In the example from the screenshot, the hover provided for the left-hand side occurrences of `opt`, `u` and `p` is `Int32 & Impure`. The other occurrences of these variables get correct type hovers.

**Comment by magnus-madsen** [comment]
Is this on master? I was just messing with this yesterday.

**Comment by magnus-madsen** [comment]
We have https://flix.dev/nightly/ but the one for today is not built yet.

**Comment by jhckragh** [comment]
Seems to be fixed in master! 🥳

![flix-hover-fixed](https://user-images.githubusercontent.com/129259/142756097-678eb07c-245a-4cde-b4d9-b6bf2da20016.png)

**Comment by magnus-madsen** [comment]
Nice. I think this was just a bug I introduced some weeks ago and now I fixed it again!
