### ISSUE TITLE
Modify notification to show whether the internal or external compiler is used

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#18]
E.g. when it says Flix x.y.z ready it should also say whether this is (internal) or (external: flix.jar).

**Comment by plougsgaard** [comment]
I suggest we only write something different (like a path or external) if an external jar is used. Alternatively we could always just provide the path it's running at?

**Comment by magnus-madsen** [comment]
OK; let us write the path.

Do we want to write the internal path though? Might tempt someone to change the file, but maybe that is okay?
