### ISSUE TITLE
Annotation different from `Deprecated` are not properly colored.

### ISSUE THREAD

**Issue by nicdard** [flix/vscode-flix#187]
![Screenshot from 2022-03-16 15-22-03](https://user-images.githubusercontent.com/55001950/158611822-7046075f-93ff-41d7-8334-d53f8dc8a429.png)

**Comment by magnus-madsen** [comment]
Interesting. Is that in the grammar or what? Should it even be colored blue?

**Comment by nicdard** [comment]
I think that having a color for the annotations is nice as most mainstream languages do it also

I will check it :)

**Comment by nicdard** [comment]
> Interesting. Is that in the grammar or what? Should it even be colored blue?

So it is defined in the grammar, but some of the annotations introduced later are missing, do you want me to add them or remove all of them? we could use a pattern actually to avoid this issues, but I am missing the information whether or not it is possible to define new annotations (I believe no)

**Comment by magnus-madsen** [comment]
I think you should just add the annotations which are supported by the compiler. I believe there is just a handful.
