### ISSUE TITLE
Goto Def for Standard Library should give a notification

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#19]
If the user tries to navigate to the source code of a standard library file we should show a notification that this is not (currently) possible.

For example, if you are using List and try to jump to the definition of Nil.

The standard library is in flux, so I suggest that the plugin simply checks whether a file exists in the workspace.

**Comment by plougsgaard** [comment]
@magnus-madsen Can be solved by looking at the `uri` checking if it's a local file or not. This might not be a good solution long term, but I'm willing to do it.

**Comment by magnus-madsen** [comment]
You mean a file in the local workspace or what do you mean by local file?

**Comment by plougsgaard** [comment]
All `uri`s registered by the plugin starts with `file://`. When Flix finds something from the standard library it's just called e.g. `List.flix`. So that's a way of differentiating between the two perhaps.

**Comment by magnus-madsen** [comment]
OK; that should be sufficient for now.
