### ISSUE TITLE
Error message is misleading when `java` not on PATH

### ISSUE THREAD

**Issue by athas** [flix/vscode-flix#198]
I was told that the language extension could not determine the version (which I guess is technically true), but the real issue is that there was no `java` executable on the path.  Telling the user explicitly to install it might be a better error message.

**Comment by magnus-madsen** [comment]
Ah. Do you remember the error message? I am not so familiar with this part of the code.

Did it crash or did it print something like `Flix requires Java 11 or later.`?

**Comment by magnus-madsen** [comment]
Or did it maybe dump something from the shell, like `java: command not found`?

**Comment by jhckragh** [comment]
Here's what I see (on Windows 10) if `java` is not on `PATH` (with version 0.74.0 of `vscode-flix`):

![flix_without_java](https://user-images.githubusercontent.com/129259/167292400-b9ac9b7a-898c-4fda-b1db-df6a1bc3870e.png)

**Comment by athas** [comment]
Yes, that looks like what I saw as well.

**Comment by topazus** [comment]
@magnus-madsen After installing flix vscode extension, the similar error message also occured for me.

```
$ java -version
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```

![image](https://user-images.githubusercontent.com/77263945/210576326-9043aaf4-52b0-4aaa-a9e9-047036128049.png)
![image](https://user-images.githubusercontent.com/77263945/210576785-0476ea41-f6a0-437b-8429-92eca6153316.png)

**Comment by magnus-madsen** [comment]
Interesting. Thanks! We are looking into it.

**Comment by magnus-madsen** [comment]
Let me know if you find a solution.

**Comment by topazus** [comment]
> Let me know if you find a solution.

pretty weird! The flix vscode extension worked today.
![image](https://user-images.githubusercontent.com/77263945/210798030-9756193a-d98e-4866-8ed3-471916a2fe5e.png)

**Comment by magnus-madsen** [comment]
@mR4smussen I think here we should just change the message to say: "Unable to find `java` on PATH. Please check that Java is correctly installed and on your PATH".

**Comment by mR4smussen** [comment]
I think this issue is a lot like the one with the [JAVA_HOME](https://github.com/flix/vscode-flix/pull/248) and I'm again not sure about getting this variable in a general way for all operating systems without actually using java. What do you think about us simply sending a general message for both variables if we are not able to use java to find the java version [here]( https://github.com/flix/vscode-flix/blob/master/server/src/util/javaVersion.ts#L40-L42) @magnus-madsen ?

("Unable to accss java. Please check that Java is correctly installed and on your PATH and JAVA_HOME")

**Comment by magnus-madsen** [comment]
I think the current solution is fine, just a question of updating the error message.

**Comment by magnus-madsen** [comment]
Fixed in master.
