### ISSUE TITLE
Connect to Flix

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#2]
The following demonstrates how to "speak" to the Flix LSP:

1. Download Flix https://flix.dev/nightly/

2. Start Flix in the background on some port (preferably on Java 14, even though 11 "should" work):

```
java -jar flix-2020-06-22.jar --lsp 8000
LSP listening on: ws://localhost:8000
```

3. Paste this into `foo.flix` (in the same directory as where you are running the jar, to keep things simple to start with):

```
def main(): Int = 123
```

4. Open a websocket (here using wscat to test):

```
wscat -c localhost:8000
```

5. Send the JSON object:

```
{ "request": "validate", "paths": ["foo.flix"] }
```

You should receive back:

```
{
  "status":"success",
  "time":"2249399031",
  "version":"v0.13.0"
}
```

6. Now try to change to program to:

```
def main(): Int = 123 + true
```

and rerun validate. You should see:

```
{
  "status":"failure",
  "results":[{
    "uri":"foo.flix",
    "diagnostics":[{
      "range":{
        "start":{
          "line":1,
          "character":19
        },
        "end":{
          "line":1,
          "character":29
        }
      },
      "severity":1,
      "code":"Type Error",
      "message":"Unable to unify the types 'Int32' and 'Bool'."
    }]
  }]
}
```

**Comment by magnus-madsen** [comment]
I made some changes to the API. It now looks more like:

```
  * Example:
  *
  * $ wscat -c ws://localhost:8000
  *
  * > {"request": "addUri", "uri": "foo.flix", "src": "def main(): Int = 123"}
  * < {"status":"success"}
  *
  * > {"request": "check"}
  * < {"status":"success","time":1749621900}
  *
  * > {"request": "context", "uri": "foo.flix", "position": {"line": 1, "character": 20}}
  * < {"status":"success","result":{"tpe":"Int32","eff":"true"}}
```

This is the file to look at:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala

**Comment by magnus-madsen** [comment]
This should make it easier to interop because now all source code is sent through the LSP. The compiler never touches the file system.

**Comment by magnus-madsen** [comment]
The api is still the same, but I made some renamings:

![image](https://user-images.githubusercontent.com/2287953/89165755-4b576800-d579-11ea-9c28-ee2790b32a73.png)

So it goes:
- api/addUri
- lsp/check
- lps/whatever

**Comment by magnus-madsen** [comment]
Everything not in lsp/* should eventually be made available as commands the user can run. E.g. `Build Project` or `Run Project Tests` etc.

**Comment by plougsgaard** [comment]
Connection has been made now. The last comment has been turned into two issues, #11 & #12 .
