### ISSUE TITLE
Update vscode-languageclient/server

### ISSUE THREAD

**Issue by nicdard** [flix/vscode-flix#203]
https://github.com/Microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server

**Comment by magnus-madsen** [comment]
@mR4smussen can we close this too?

**Comment by mR4smussen** [comment]
Yes, this was solved by https://github.com/flix/vscode-flix/pull/204 and vscode-languageserver was updated to 8.0.2 in https://github.com/flix/vscode-flix/pull/236
