### ISSUE TITLE
Pass arguments to LSP

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#208]
It looks like the `ExtraFlixArgs` parameters are only passed to the `run`, `test`, etc. commands

This is preventing me from using the `--Xeffects` option in LSP

**Comment by magnus-madsen** [comment]
Hmm

**Comment by mlutze** [comment]
I've made a bit of progress on this. In addition to the plugin not passing along the options, the LSP stuff on the compiler's side does not maintain the original command line options as it launches the Flix instance. The whole `Main.scala` file is a bit of a mess with a lot of stateful checks; a hacky solution is of course possible, but a refactor of that and related files, along with the command line args in general would be nice. (See https://github.com/flix/flix/issues/3720)

**Comment by magnus-madsen** [comment]
(We can always toggle the flag and build a custom flix jar for testing).

**Comment by magnus-madsen** [comment]
I suggest to iterate on the implementation until it works a bit better and then we can ask Stephen how much breakage there is.
