### ISSUE TITLE
What should happen with CodeLenses when the document does not compile?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#21]
For example, we current can have the situation where:

![image](https://user-images.githubusercontent.com/2287953/93992923-7185d100-fd8e-11ea-9b62-6dc21cd8111d.png)

Since there is an error in main2 it does not make sense that you should be able to click "Run Main" imo.

**Comment by plougsgaard** [comment]
I have handled this by by-passing Flix if errors exist 925d1279dbf39bb4029117ccf56a2d17fd6241cf.

**Comment by magnus-madsen** [comment]
CodeLenses now sometimes take a long time to show up or do not show up at all (?)

**Comment by magnus-madsen** [comment]
Sometimes they are also not hidden:

![image](https://user-images.githubusercontent.com/2287953/94335749-f155aa80-ffdd-11ea-94de-69dfde1d0209.png)

**Comment by magnus-madsen** [comment]
Renaming main2 to main fixes the issue and hides the codelens

**Comment by magnus-madsen** [comment]
We discussed that code lenses should stay visible, but report an error when executed, if the the document contains errors.

**Comment by plougsgaard** [comment]
Fixed by 0d50561938ffc71c695c437a55fe509b32172cac.
