### ISSUE TITLE
Allow custom compiler path

### ISSUE THREAD

**Issue by locriacyber** [flix/vscode-flix#210]
This extension doesn't support custom compiler path yet. I hope it does, because I put `flix.jar` in some other place.

I'm not sure how should I add this feature. I tried, but failed. See https://github.com/flix/vscode-flix/pull/209

Also, I hope this extension looks for `flix` on PATH.

**Comment by magnus-madsen** [comment]
Do you think we should add an option the plugin where you can specify the path?

**Comment by locriacyber** [comment]
Yes. Also add bundling and don't include every file in this repo.

**Comment by magnus-madsen** [comment]
> Yes. Also add bundling and don't include every file in this repo.

What do you mean by bundling?

**Comment by locriacyber** [comment]
With rollup or esbuild and `.vscodeignore`. Currently running `vsce package` includes every file in this repo.

**Comment by magnus-madsen** [comment]
> With rollup or esbuild and `.vscodeignore`. Currently running `vsce package` includes every file in this repo.

Right. That is tracked in https://github.com/flix/vscode-flix/issues/70.

**Comment by manoj2601** [comment]
Maybe I can help with this issue. We can add a box in the extension settings where the users can provide the custom path for Flix compiler. (if they want to put flix.jar in some other places).

Users can provide the custom path as follows:
![image](https://user-images.githubusercontent.com/45541010/194701483-98637aa8-ec2a-4412-8f64-91462588dabb.png)

PR for this issue #225

**Comment by magnus-madsen** [comment]
At the moment, we do not plan to support this feature.
