### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#22]
I receive a `Request textDocument/hover failed` error when I hover over `main` in this file.

File content:
```
def main(): Int = {
    123
}
```

Error stacktrace:
```
[Error - 9:08:48 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/matt/.vscode/extensions/flix.flix-0.3.0/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/matt/.vscode/extensions/flix.flix-0.3.0/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at /home/matt/.vscode/extensions/flix.flix-0.3.0/client/node_modules/vscode-languageclient/lib/client.js:2208:28
	at async /home/matt/.vscode/extensions/flix.flix-0.3.0/client/out/extension.js:23:9
```

Other details:
```
$ java --version
openjdk 13.0.3 2020-04-14
OpenJDK Runtime Environment (build 13.0.3+3-Ubuntu-1ubuntu2)
OpenJDK 64-Bit Server VM (build 13.0.3+3-Ubuntu-1ubuntu2, mixed mode)
```

```
$ code --version
1.49.2
e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
x64
```

**Comment by magnus-madsen** [comment]
There is a "known" issue with multi-line expressions on the compiler-side. Not sure how this is revealed on the client side.

**Comment by magnus-madsen** [comment]
Although if the hover is over main, not sure what should be happening.

**Comment by magnus-madsen** [comment]
If you are hovering over "main" nothing is displayed, because the compiler does not send anything.

What do you want the compiler to display when hovering over the name of a function?

**Comment by mlutze** [comment]
This actually seems to happen no matter what I hover over. Either I get a `Loading` tooltip which never seems to load, or I get the error popup and the stack trace. Is this an installation issue?

**Comment by magnus-madsen** [comment]
Do any of the features, except for syntax highlight, work? It sounds like maybe it does not start correctly.

Do you see a notification that it has started?

**Comment by magnus-madsen** [comment]
Can you try to download the newest nightly flix.jar and put it into the root of workspace folder?

**Comment by mlutze** [comment]
Nightly jar works!

**Comment by magnus-madsen** [comment]
OK; problem was an old version of the internal flix.jar. You should be able to do ctrl+shift+p and download a new updated version.

A question is how we should keep future versions of the plugin and flix in sync.

**Comment by plougsgaard** [comment]
We discussed this the other day too. Let's open an issue when/if we wish to do more in this area.
