### ISSUE TITLE
Prioritization of tasks for student programmer

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#231]
Initial Tasks:
- [x] #232
- [x] #70 
- [x] #91
- [x] Ensure that "Flix Restart" works
- [x] #152
- [x] #221
- [x] #247

Next:
- [x] Find and fix any use of deprecated functionality
- [x] #174 and #191
- [x] https://github.com/flix/vscode-flix/issues/198
- [x] https://github.com/flix/flix/issues/5306

Next:
- [ ] #233
- [ ] Add right-click show AST using `ShowAstProvider` https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala

Next:

- [x] #234
- [ ] #202

Other:
- [ ] Refactor flix/flix.dev and flix/play.flix.dev to have a directory of samples that is then turned into a dropdown.
  - [ ] https://github.com/flix/play.flix.dev/issues/3
- [ ] Introduce a "Ace" mode for Flix syntax. (see  https://github.com/flix/highlightjs-flix/blob/master/src/flix.js )
  - [ ] Upstream if possible, otherwise we create a repo under flix org.
  - [ ] Use mode on flix.dev and play.flix.dev
- [ ] https://github.com/flix/play.flix.dev/issues/9

**Comment by mR4smussen** [comment]
> Find and fix any use of deprecated functionality 

I have gone through all files in the repo and didn't find anything marked as deprecated.

**Comment by magnus-madsen** [comment]
@mR4smussen What's next? :)

**Comment by mR4smussen** [comment]
I have been looking at https://github.com/flix/vscode-flix/issues/191, but I’m not completely sure about in which parts of the command we wish to escape special characters. As discussed [here]( https://github.com/flix/flix/issues/2762), we are currently using a library which takes an Array and makes it into a string in which special characters are escaped. 

Right now, I am simply working through the list from top to bottom :)
