### ISSUE TITLE
Upgrade JavaScript dependencies

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#232]

**Comment by magnus-madsen** [comment]
Reopened until:
- Warning in debug terminal is fixed.
- Dependabot issues resolved.

**Comment by mR4smussen** [comment]
I believe both the dependabot issues (https://github.com/flix/vscode-flix/pull/238, https://github.com/flix/vscode-flix/pull/237) and the warning in the debug terminal has been fixed. The warning being handled by https://github.com/flix/vscode-flix/pull/239.
I think this issue can be closed @magnus-madsen?

**Comment by magnus-madsen** [comment]
Yes, thanks!
