### ISSUE TITLE
Verify Flix as publisher on VSCode market place

### ISSUE THREAD

**Issue by jaschdoc** [flix/vscode-flix#254]
This probably has very low priority but it just occurred to me that the Flix extension doesn't have the blue check mark in VSCode. This requires submitting a file that argues ownership of flix.dev so it shouldn't be that difficult.

See [Verify a publisher](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher) and [Eligble domains](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#eligible-domains)

**Comment by magnus-madsen** [comment]
I tried, but Microsoft is broken. Maybe another time.
