### ISSUE TITLE
Add `Show Ast` options for the ASTs we want to show

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#263]
Searching for `Typed Ast` will probably tell you where to make changes.

**Comment by JonathanStarup** [comment]
I would like to have it for phases instead of asts. is this okay?

**Comment by magnus-madsen** [comment]
Seems reasonable. Do we just give them the name of the phase?

**Comment by JonathanStarup** [comment]
Maybe just `Typer` creates `TyperAst` etc
