### ISSUE TITLE
main() in 2 files

### ISSUE THREAD

**Issue by igr** [flix/vscode-flix#282]
If we open a folder in VSCode that contains 2 flix files, and each contains the `main()` function, the Flix compiler will complain:

```
>> Duplicate definition of 'main'.
```

That is correct, however, is there a way to have multiple flix files with `main` functions in the same folder and run each file separately in the VSCode? This is useful for the examples.

**Comment by magnus-madsen** [comment]
Its not really possible because VSCode works in the "project/workspace mode". You would have to either create separate directories or alternative use modules (then you can have A.main and B.main).

**Comment by igr** [comment]
Make sense! Thank you!
