### ISSUE TITLE
Repl is not started

### ISSUE THREAD

**Issue by igr** [flix/vscode-flix#292]
I have Flix project with `flix.jar` in the project root.

When I click on the `Run` hint in the code (above the e.g. `main` function), I see the following:

```
java -jar /Users/ispasic/prj/igr/void/flix/flix.jar repl 
java version "11.0.15" 2022-04-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15+8-LTS-149, mixed mode)

ispasic:void/flix on  master via ☕ v11.0.15 
❯ :eval main()
fish: Unknown command: :eval
```

In other words, REPL is not started. When I run it manually, everything works. It looks like a timing issue, as the `java -jar /Users/ispasic/prj/igr/void/flix/flix.jar repl ` is logged first, before java versions (that are being printed by my shell).

Workaround: I run `java -jar /Users/ispasic/prj/igr/void/flix/flix.jar repl ` manually in the VSC terminal.

Note: removing `flix.jar` does not change a thing, repl is not started

**Comment by magnus-madsen** [comment]
Hmm. Strange. Thanks for the report.

**Comment by magnus-madsen** [comment]
@sockmaster27 I think #279 introduced a bug, because it seems that no Flix REPL is currently started by VSCode (?)

**Comment by magnus-madsen** [comment]
@sockmaster27  Or rather it seems that `REPL` is created but the Java Flix command is not run.

Please have a look when possible. Thanks!
