### ISSUE TITLE
Check Java Version

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#3]
When the extensions starts, it should ensure that the currently installed Java version is compatible with Flix.

In practice, I suggest that the extension executes:

```
java -version
```

If the command is not found, it shows a popup error message telling the user to install Java (LSP has a command for this).

If the command exists, we get something like:

```
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)
```

Now I am not sure of how this format can look, but it needs to be parsed up. Maybe there is a package?

Flix currently requires Java 11, so it should check against that, and allow any higher version.

If Java is too old it should show an error message, ideally including:

- The required version (currently Java 11)
- The found version (e.g. Java 8)
- The path where java was found (Not sure exactly how this would work).

The plugin in should then fall back to some kind of "no-op" mode or similar.

**Comment by plougsgaard** [comment]
Solved in 79cc3de32100c745f9de58410cfa5d4a15f9527e.

**Comment by magnus-madsen** [comment]
Just to confirm: What happens if there is no java version installed at all?

**Comment by plougsgaard** [comment]
If no `java` is installed it will report "unknown version" and prompt for the user to get Java 11+.
