### ISSUE TITLE
Multiple open files containing same function names

### ISSUE THREAD

**Issue by racerand** [flix/vscode-flix#30]
If I have 2 files open simultaneously and they contain functions with the same names I get a `dublicate name error`. The files are not connected. I have only tested with identical files with different names. 
Most errors go away if I change the name, but main is a bigger problem. Since this is the only entry point it is the only function that doesn't need to be used. But when I have a main function in each file, I get a `dublicate name error`, but if I change the name of one, I get a `Unused definition (Redundancy Error)`.
I have tested with the files both in the same folder, and separate folders.

**Comment by magnus-madsen** [comment]
Are the files using different namespaces?

Flix / VSCode uses the "workspace" metaphor. All files in a workspace are considered to be part of the same project and hence cannot declare the same names twice. 

Consequently, an entire project cannot have more than one main.

**Comment by magnus-madsen** [comment]
To avoid ununsed def, you can always stick a `pub` in front or rename with an underscore.

**Comment by racerand** [comment]
I have not declared an explicit namespace of the files no. But e.g. for writing a lot of Flix test programs, having the assumption that all files are part of the same project, this meaning that they intertwine, does not hold.

**Comment by racerand** [comment]
I have not declared an explicit namespace of the files no. But e.g. for writing a lot of Flix test programs, having the assumption that all files are part of the same project, this meaning that they intertwine, does not hold.

**Comment by magnus-madsen** [comment]
> 
> 
> I have not declared an explicit namespace of the files no. But e.g. for writing a lot of Flix test programs, having the assumption that all files are part of the same project, this meaning that they intertwine, does not hold.

I am not sure how the compiler can know what files to include and exclude.

For example, in Java you typically have a src folder and everything in that folder is in scope. (You cannot have two classes with the same name).

**Comment by racerand** [comment]
That is a valid point. The solution is to encapsulate the file in a namespace, as you usually encapsulate it in a class in Java.

I tried this, and while it allows for multiple main functions, the `run main` feature of the plugin does not work under these conditions.

**Comment by magnus-madsen** [comment]
I think there are two issues at tension:

- We have a principle that states that every Flix program has a single entry point and no code is executed before it.
- We want to be able to "click" on a piece of code in VSCode, run it, and see its output.

Not sure how to reconcile that. 

Perhaps we should have some "Run This Function" code lens (?). This would require some compiler trickery...

**Comment by magnus-madsen** [comment]
I am closing this. The discussion continues in: https://github.com/flix/flix/issues/977
