### ISSUE TITLE
add back `:doc` command

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#303]

**Comment by sockmaster27** [comment]
Looks like it's already there? 🤔

**Comment by magnus-madsen** [comment]
is it?

![image](https://github.com/flix/vscode-flix/assets/2287953/b17c95af-19bc-46aa-b0f9-6794744cf4de)

**Comment by magnus-madsen** [comment]
@sockmaster27 Ping

**Comment by sockmaster27** [comment]
Ah, thought you meant in the REPL
