### ISSUE TITLE
One error stops execution

### ISSUE THREAD

**Issue by racerand** [flix/vscode-flix#31]
I noticed that if there is one error (I have a dublicate name error), then the rest of the file does not seem to be passed. I'm guessing this is because of the way the compiler is built, but I would still expect to be able to look up different parts of the code, and not be forced to deal with it before I can look at something else.

The bigger issue for me however is that the error also  breaks other functionality, like being able to see the type of an expression by hovering over it with the cursor. This I could only replicate if the error exists when VScode is opened, and not if it occurs while coding.

**Comment by magnus-madsen** [comment]
If the program is broken there is little we can do, but perhaps we should show some notification if the user tries to goto def/hover/rename etc. while the document is broken?

I guess we also lack some special handling if the document is broken *upon startup*.

**Comment by magnus-madsen** [comment]
We will eventually fix this, but it depends on a major restructuring of the compiler to work with incomplete/buggy programs. Consequently, everything is currently working as intended, even if not ideal from the point of view of the programmer.
