### ISSUE TITLE
Rework the ShowAst functionality

### ISSUE THREAD

**Issue by JonathanStarup** [flix/vscode-flix#315]
Right now a lot of the phases have changed names so a lot of `Show XAst` is broken. We we add capability to ask the compiler for its phases.

Additionally, `Show XAst` implicitly has the `<Root>.main` entrypoint, so often most the ast is deleted if you don't use that main name. It should really be `Show XAst for Something.example` (where the given function must be a valid entrypoint).

**Comment by JonathanStarup** [comment]
right, that makes sense. it could also be that the user presses "show ast" then the plugin asks the compiler that then shows a dropdown of the phases.


But yeah i like the solution where the user types it themselves

**Comment by magnus-madsen** [comment]
I have decided on the following: We change the ShowAst functionality to prompt for the phase name. Hence VSCode no longer needs to know about any phases. On the compiler side, we can use levensthein distance, such that if you type e.g. `Reduc` it is good enough.

@sockmaster27 Will you implement the change on VSCode
@JonathanStarup Will you improve the compiler side?

**Comment by magnus-madsen** [comment]
@sockmaster27 and @JonathanStarup Gentle Ping :)

**Comment by magnus-madsen** [comment]
@JonathanStarup You should check that it works as you would expect.
