### ISSUE TITLE
'Compile On Change: Delay' is used for everything except compiling on change

### ISSUE THREAD

**Issue by sockmaster27** [flix/vscode-flix#318]
`handleSave` and `handleChangeContent` both skip the delay because it breaks the auto-completions.
With delay skipped:
![image](https://github.com/flix/vscode-flix/assets/61235930/91d75785-987d-45ee-9239-ee8f13e14a66)
With delay:
![image](https://github.com/flix/vscode-flix/assets/61235930/a795e975-58fa-419d-9ec6-f291f0c0567f)

I see 2 options:
- The setting and its accompanying logic should be removed.
- The auto-completion mechanism should somehow be fixed to tolerate this, and the delay should not be applied to anything other than `handleChangeContent`.

**Comment by magnus-madsen** [comment]
The delay is necessary because we cannot hit the compiler on every keystroke.

I think the auto-completion issue is separate and will be solved by the resilient parser.

**Comment by sockmaster27** [comment]
> The delay is necessary because we cannot hit the compiler on every keystroke.
> 
> I think the auto-completion issue is separate and will be solved by the resilient parser.

But it has been like this at least since I started I'm pretty sure

**Comment by magnus-madsen** [comment]
The delay exists not to hammer the server, so removing that makes little sense. But maybe you are proposing something else?
