### ISSUE TITLE
Syntax highlighting fails in presence of character literals

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#32]
Highlighting fails for the entire line when there is a character literal in the line.

Example:
```
        match parseStar(chars) {
            case Some(left, '|' :: tail) => Some(left, '|' :: tail)
            case Some(left, ')' :: tail) => Some(left, ')' :: tail)
            case Some(left, '*' :: tail) => Some(left, '*' :: tail)
            case Some(left, Nil) => Some(left, Nil)
            case Some(left, leftRest) =>
                match parseConcat(leftRest) {
                    case Some(right, rightRest) => Some(Concat(left, right), rightRest)
                    case None => None
                }
            case None => None
        }
```

Lines 2-4 have no highlighting.

**Comment by magnus-madsen** [comment]
I can confirm, but I have no idea why this happens. The code is here:

https://github.com/flix/vscode-flix/blob/master/syntaxes/flix.tmLanguage.json#L158

if anyone wants to take a guess.

**Comment by racerand** [comment]
Which color  is the expected color  of it?

**Comment by magnus-madsen** [comment]
Don't know. The grammar is separate from the color theme in VSCode.

**Comment by mlutze** [comment]
Could it be related to the fact that the `name` field is capitalized?

**Comment by magnus-madsen** [comment]
That does look suspicious...

**Comment by magnus-madsen** [comment]
Fixed in master.
