### ISSUE TITLE
Diagnostics - Longer Error Messages

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#35]
For the diagnostics, and until LSP support improves, I think we should add support for a "full length" error message being shown in one of the outputs.

**Comment by magnus-madsen** [comment]
A diagnostic now includes a "fullMessage" that contains the entire error message.

**Comment by plougsgaard** [comment]
@magnus-madsen does this work "as is" or does it require work in this repo?

**Comment by magnus-madsen** [comment]
It requires work in this repo. You need to take `fullMesage` and show it in the output.

**Comment by plougsgaard** [comment]
Gotcha.
