### ISSUE TITLE
add `Flix: init`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/vscode-flix#358]
It would be a nice way to initialize a project without making a flix file first

**Comment by magnus-madsen** [comment]
You just want the `init` command?

**Comment by JonathanStarup** [comment]
Yeah, when i open vscode in a new folder, I don't have a flix jar on hand, and the path of the vscode flix jar is too long to remember. Right now I create tmp.flix to make flix startup and then use that to init. It would be nicer just to run `Flix: init` in vscode

**Comment by mlutze** [comment]
> Yeah, when i open vscode in a new folder, I don't have a flix jar on hand, and the path of the vscode flix jar is too long to remember. Right now I create tmp.flix to make flix startup and then use that to init. It would be nicer just to run `Flix: init` in vscode

You don't have Flix on your path? :O

**Comment by magnus-madsen** [comment]
@sockmaster27 Can we support this? I don't know if the command needs to differ from the rest because the folder is empty (as Jonathan explains).

**Comment by sockmaster27** [comment]
Add a download link to flix.dev and have an installer that puts it in you path?

**Comment by magnus-madsen** [comment]
No no. A command that you can run, like Flix: test and Flix: check

**Comment by magnus-madsen** [comment]
But this one has to run the init command.

**Comment by sockmaster27** [comment]
> But this one has to run the init command.

I believe we already have the `init` command which also works in an empty folder.
I understand @JonathanStarup to mean that we aren't supporting the case of initting a project in an empty folder very well, because "C:\Users\user-name\AppData\vscode\globalStorage\flix.flix\flix.jar" or whatever isn't very easy to remember.

**Comment by JonathanStarup** [comment]
> I believe we already have the init command

But not as a vscode action it seems

`Flix: Build` fx work on an empty folder (or at least it starts the reply) so I don't think `Flix: init` would be different from that

**Comment by sockmaster27** [comment]
> > I believe we already have the init command
> 
> But not as a vscode action it seems
> 
> `Flix: Build` fx work on an empty folder (or at least it starts the repl - to really build you have to do it twice) so I don't think `Flix: Init` would be different from that

Ah, okay 👍
