### ISSUE TITLE
Use `createTerminal` to launch the Flix terminal?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#372]
Can we use:

```
createTerminal(name?: string, shellPath?: string, shellArgs?: string | readonly string[]): [Terminal](https://code.visualstudio.com/api/references/vscode-api#Terminal)
```

to actually create terminal backed by Flix (i.e. by running `java -jar flix.jar` from the cwd)?

See https://code.visualstudio.com/api/references/vscode-api

**Comment by magnus-madsen** [comment]
Something like this seems to work:

```
    FLIX_TERMINAL = vscode.window.createTerminal('REPL', 'C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.0.35-hotspot\\bin\\java.exe', ['-jar', 'C:\\tmp\\flix\\flix.jar'])
```

**Comment by sockmaster27** [comment]
What's the motivation for doing this? Remember that we still need `launchReplInTerminal()` [here](https://github.com/flix/vscode-flix/blob/master/client%2Fsrc%2Fhandlers%2Fhandlers.ts#L35).

**Comment by magnus-madsen** [comment]
It should avoid that, i.e. instead of having a shell that is running the Flix shell, we just run the Flix shell directly.

**Comment by magnus-madsen** [comment]
This means if the shell dies (e.g. user exit or crash), we can actually restart it.

**Comment by magnus-madsen** [comment]
i.e. the _Flix repl_ becomes _the shell_.
