### ISSUE TITLE
Handle stdout and stderr from Flix thread

### ISSUE THREAD

**Issue by plougsgaard** [flix/vscode-flix#39]
Current suggestion is to just print all of this to the extension's output.

**Comment by magnus-madsen** [comment]
This program can be used to test:

```
def main(): Int = null as Int
```

I think the error should not show up as a notification, but in one of the two outputs.

**Comment by magnus-madsen** [comment]
Running this program produces no output (but it should):

```
def main(): Int = ?hole
```

(Not sure if the problem is in the compiler or in the plugin)

**Comment by magnus-madsen** [comment]
I think this mostly works, except that we should offer the user to restart Flix

**Comment by magnus-madsen** [comment]
The running main notification also persists.

**Comment by plougsgaard** [comment]
The original issue is fixed in 78de22816c372d882c74d512db624bc4f628d477.
