### ISSUE TITLE
[Windows] Extension installation fails, quoting "fetch undefined".

### ISSUE THREAD

**Issue by eikopf** [flix/vscode-flix#397]
After installing the extension, and when opening a folder containing _only_ an empty file called `Main.flix`, VSCode produces a vague error about `fetch` being undefined.

> Cannot install extension: `fetch` is not defined.

At least for me, the solution was to run `npm install --global node-fetch` and then completely restart VSCode. Is there a way to use a function from `node-core`, or is this a VSCode-on-Windows issue?

**Comment by magnus-madsen** [comment]
Hi @eikopf and thanks for the bug report.

(I have been away, hence the long response).

What version of VSCode were you using? Newer version come with fetch built-in so there should not be any issue.

It should just "work out of the box".

**Comment by magnus-madsen** [comment]
Can you offer some more details? VSCode Version? Windows version?

(We have multiple machines with Windows where it works currently, so any extra information would be useful).

@sockmaster27 Do you have any ideas other than outdated VSCode?

**Comment by magnus-madsen** [comment]
Maybe relevant: https://stackoverflow.com/questions/73941369/vscode-extension-api-fetch-is-not-defined

**Comment by eikopf** [comment]
> Can you offer some more details? VSCode Version? Windows version?
> 
> (We have multiple machines with Windows where it works currently, so any extra information would be useful).
> 
> @sockmaster27 Do you have any ideas other than outdated VSCode?

This was on VSCode 1.88.0 and Windows 22H2 (specifically build 22621.3447). I checked to see if I was wildly behind on VSCode versions, but installing the updates available only gave me 1.88.1.

It's entirely possible that I happened to be on an older version of VSCode when I installed the Flix extension, and that restarting it just happened to also apply the update that included node-fetch in VSCode's version of node. Admittedly, I can't reproduce the bug (even by uninstalling node-fetch with npm), so my suspicion is that that's what happened.

**Comment by eikopf** [comment]
I'd suggest that if your Windows machines don't have this issue, then it's probably enough to call this expected behaviour for using an out-of-date version of VSCode.

**Comment by magnus-madsen** [comment]
> I'd suggest that if your Windows machines don't have this issue, then it's probably enough to call this expected behaviour for using an out-of-date version of VSCode.

I strongly suspect this to be the case.

**Comment by sockmaster27** [comment]
I agree. The newer releases of the extension should declare the minimum supported VS Code version correctly. 
What might have happened is that VS Code grabbed an older release that (incorrectly) claimed to support its version.
Perhaps we should just yank all releases except the newest?

**Comment by sockmaster27** [comment]
@magnus-madsen Is this possible?

**Comment by magnus-madsen** [comment]
> @magnus-madsen Is this possible?

Not sure, but I would rather not mess with it.

As I see it, this problem disappears with time and we can leave this ticket as documentation, if someone else should have the same problem.
