### ISSUE TITLE
Install Flix

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#4]
When the extension starts it should promp the user to download Flix into the extension VSCode folder.

https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage

Iteration 1 might look something like:

- Download Flix to VSCode extension? (OK to continue).
- Downloads a hard coded version into `ExtensionContext.globalStoragePath`.

Iteration 2 might be even more fancy:
- Promps the user with a list of snapshots from https://flix.dev/nightly/. (Note: It is fine to assume that there is a snapshot for every date; we don't have to scrape and parse the HTML from that page).
- Downloads the version into `ExtensionContext.globalStoragePath`.

Iteration 3 might be more fancy:

- Uses the GitHub API to retrieve a list of releases. Prompts the user for which one to retrieve.
- Downloads the version into `ExtensionContext.globalStoragePath`.

These steps only happen when no `flix.jar` is available in `ExtensionContext.globalStoragePath`. Of course if Flix has already been downloaded then there is no reason to go through this again. (Although later we may want an update button).

Note: The user is responsible for ensuring that Java is installed (see #3).

**Comment by magnus-madsen** [comment]
I have a proposal for a slight refinement:

If the project root directory contains a "flix.jar" then that is used as the current compiler.

Otherwise the plugin downloads (to some ExtensionContext.globalStoragePath) the Flix compiler and uses that.

This would be very useful because most ordinary uses will just go with the default, but for us developers we will often have a need to experiment with a custom build compiler and then we can simply dump the jar in the root.

**Comment by plougsgaard** [comment]
I believe this is handled by #37 and #57
