### ISSUE TITLE
Allow refactoring even in the presence of errors

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#405]
i.e. remove the check

**Comment by sockmaster27** [comment]
I can't seem to get the refactorings to show up in the way I'd expect them to. Could you give an example?

**Comment by magnus-madsen** [comment]
> I can't seem to get the refactorings to show up in the way I'd expect them to. Could you give an example?

Try to rename a variable while the program has a syntax error.

**Comment by magnus-madsen** [comment]
@sockmaster27 If we can get this one done and then the socket thing then I can we can move on.
