### ISSUE TITLE
Cannot set properties of undefined (setting 'userConfiguration')

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#427]
[Error - 8:19:12 PM] Notification handler 'ext/replaceConfiguration' failed with message: Cannot set properties of undefined (setting 'userConfiguration')

**Comment by sockmaster27** [comment]
Can you recreate it?

**Comment by magnus-madsen** [comment]
It happens every time I start VSCode

**Comment by sockmaster27** [comment]
Where is the error displayed?
What does your user/workspace configuration look like?

**Comment by magnus-madsen** [comment]
Its during startup.

**Comment by sockmaster27** [comment]
Have you changed any Flix-specific settings i VS Code?

**Comment by magnus-madsen** [comment]
No. They show default.
