### ISSUE TITLE
An improvement for "Flix Errors" Output

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#43]
Imagine the following:

I have multiple failing test cases:

![image](https://user-images.githubusercontent.com/2287953/96235655-57a96980-0f9b-11eb-8cb8-afef896e0f33.png)

I am investigating and I make a small change (e.g. changing true to false). But now the editor automatically shows me:

![image](https://user-images.githubusercontent.com/2287953/96235777-7dcf0980-0f9b-11eb-98d7-38984814e9fc.png)

which breaks my workflow.

I think that when document successfully compiles we should clear that output, but we should not print "No errors" nor should we switch focus to it. Perhaps we should never switch focus or maybe we should only switch focus if there is an error. At least if there is no error, there is no reason to switch focus.

**Comment by plougsgaard** [comment]
I like switching focus when there are errors only. However errors are going to be present pretty often when you're in the process of writing code when we make the checks as often as we do, and not just on save. Hm.

**Comment by magnus-madsen** [comment]
Hmm. At least we should not show "No Errors" because it keeps flickering.

**Comment by plougsgaard** [comment]
Oh yeah it will clear and write the same text again. Let me summarise:
- Don't repeatedly show no errors (causes flickering)
- Don't automatically switch to "Flix Errors" output (but still switch to "Flix Extension" output when running main/tests

**Comment by magnus-madsen** [comment]
I think so yeah
