### ISSUE TITLE
Arrow color when no space

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#442]
We use `->` without space around it for struct field access:

![image](https://github.com/user-attachments/assets/a037cab1-bba2-40f2-be2e-bc4f41af15aa)

@sockmaster27 Do you think it would be possible to give it a different color? I tried messing around in the grammar file, but I was unsuccessful.

**Comment by sockmaster27** [comment]
I can fix it in the normal VS Code color scheme, but it's sort of a problem that the Flixify theme makes all keywords and operators the same color, so the only way to get it to be different is either to not categorize it as anything, or to categorize it as like a string literal or something.

I don't know if such semantic abuse could hurt anything (I'm specifically thinking of Linguist that does more than just highlighting), but it at the very least feels wrong, and it might be a problem with other third party themes.

Could we change the Flixify theme to accommodate this?

**Comment by magnus-madsen** [comment]
I suppose I never thought about whether -> is a keyword or an operator. 

What if I want it to be neither?

**Comment by sockmaster27** [comment]
> I suppose I never thought about whether -> is a keyword or an operator.
> 
> What if I want it to be neither?

It just needs to be in a category that the different color themes recognize, and it looks like the standard way to categorize an operator is called `keyword.operator` for whatever reason. I don't believe there's any reason for it to match the philosophy of the language one to one, but it's probably not great to suddenly categorize the arrow as a number literal or something like that.

I've found that categorizing the function arrow as a regular keyword and the struct arrow as an operator happens to work fairly well with most of the default themes, just not Flixify:
![image](https://github.com/user-attachments/assets/6aeca766-1ab2-4059-b1b0-1da9bf27ca68)
![image](https://github.com/user-attachments/assets/d31ca322-0e70-4402-916a-1a476ffa59fc)
![image](https://github.com/user-attachments/assets/590b59d0-5b2a-4978-bfcb-c50e8617f0b4)

**Comment by magnus-madsen** [comment]
Thanks for all the info. Very helpful. Ill talk to @dghosef and see what he thinks.

**Comment by sockmaster27** [comment]
> What is `.` classified as(if anything)?

It's not categorized as anything currently.

**Comment by dghosef** [comment]
It sort of feels that `->`, `#`, and `.` have similar enough purposes that they should be highlighted in the same fashion
