### ISSUE TITLE
IDE is endlessly losing connection to flix server

### ISSUE THREAD

**Issue by dsv57** [flix/vscode-flix#444]
There is endless stream of 'Connection to the flix server was lost, trying to reconnect...' in Output tab at the bottom.

**vscode-flix:** 1.31.0 (latest from git, packaged by myself)
commit 81b134c6ed16e88a6ea904ddc91382d2dfc74995

**VSCode:** [Uncoded](https://gitlab.com/megastallman/uncoded/) (latest deb package) — just original VSCode with telemetry domains replaced with 0.0.0.0.
Version: 1.92.0
Commit: 0426dd4e2a555f71d003d1abef455d0301a06bd0
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.1.0-21-amd64

**OpenJDK** version "21.0.4" 2024-07-16 LTS (latest from Adoptium) installed separately and added to `$PATH`.
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

Also, it will be good, if you will start publishing `.vsix` files to https://open-vsx.org/ or just Github Releases ;)

**Comment by magnus-madsen** [comment]
Thanks @dsv57 for the report. Would it be possible for you to checkout (from Git) and earlier version of the flix-vscode extension? Specifically, 1.30.0 and try that?

**Comment by magnus-madsen** [comment]
@sockmaster27 Could you help debug this with high priority? (Although I suspect we need more information to reproduce).

**Comment by magnus-madsen** [comment]
@dsv57 Do you know if:

1. The extension used to work before?
2. The extension manages to connect and then only later enters some reconnect loop?
3. What is the frequency between reconnects? Like seconds or less?
4. You are on Linux-- any firewall or other thing that might prevent binding to a port?

**Comment by dsv57** [comment]
P.S. After closing IDE, `flix.jar lsp` process is still running.
And may globally installed OpenJRE 17 have any influence on this? I'll try to export some Java env vars now, pointing to modern JRE.

**Comment by magnus-madsen** [comment]
A wrong Java version on your path could be a problem.. But then there should have been a message.

**Comment by dsv57** [comment]
Have exported all Java variables:
`export JAVA_HOME=$HOME/dev/jdk-21.0.4+7-jre
export JRE_HOME=$HOME/dev/jdk-21.0.4+7-jre
export CLASSPATH=$HOME/dev/jdk-21.0.4+7-jre/lib
export PATH=$HOME/dev/jdk-21.0.4+7-jre/bin:$PATH` 
It is just trying to reconnect every ~4 seconds now. :)

**Comment by magnus-madsen** [comment]
And you see a Java process? (Is it the right Java version)?

Does `lsof -i -n -P|grep LISTEN` show some port as bound to?

**Comment by magnus-madsen** [comment]
> It is just trying to reconnect every ~4 seconds now. :)

Yeah, it uses a small pauses and then larger and larger pauses. But I suppose the problem here is that the connection is never established to begin with.

**Comment by magnus-madsen** [comment]
If you restart everything, do you see either:

- Flix 0.50.0 Ready! or
- Failed starting Flix

?

**Comment by dsv57** [comment]
Just now installed previous version of extension, `flix@1.30.0`.
After opening Flix project, IDE showed `The terminal process "/usr/bin/bash" failed to launch (exit code: 1)` notification. And after downloading flix.jar dumped this:
```
Listen on 'localhost/[0:0:0:0:0:0:0:1]:8891'.
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8891
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
Emitted 'error' event on e instance at:
    at xs (/home/user/.vscode-oss/extensions/flix.flix-1.30.0/server/out/server.js:37:40731)
    at ClientRequest.<anonymous> (/home/user/.vscode-oss/extensions/flix.flix-1.30.0/server/out/server.js:37:38972)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8891
}

Node.js v20.9.0
[Info  - 18:50:43] Connection to server got closed. Server will restart.
```

**Comment by magnus-madsen** [comment]
Assuming the process is still running on  127.0.0.1:8891, can you `telnet 127.0.0.1 8891` or do you also get a connection refused?

**Comment by dsv57** [comment]
I have already returned new extension, but when i tried to open LSP port (8888) in the browser it said `404 WebSocket Upgrade Failure`. And later, when previous process was not killed IDE allocated new port, 8889.

**Comment by magnus-madsen** [comment]
That's strange because then it seems the server is ready...

**Comment by dsv57** [comment]
Hm, telnet says `Connection refused`, but browser `404 WebSocket Upgrade Failure`.
`lsof` confirms, that it runs under new JRE.

**Comment by dsv57** [comment]
It accepts `localhost`, but refuses `127.0.0.1`!

**Comment by magnus-madsen** [comment]
Hmm.. Does suggest some routing issues.

**Comment by magnus-madsen** [comment]
![image](https://github.com/user-attachments/assets/9751d635-9602-4b06-baed-7f87491e735b)

Debian 12.6 in VirtualBox with Java 21 from Oracle and VSCode from Microsoft both direct deb packages.

**Comment by magnus-madsen** [comment]
Bizarrely, we used to have a problem where using 'localhost' would not use. 

Hence we found https://github.com/microsoft/vscode/issues/192545 and the switched to using '127.0.0.1'.

But now you have the opposite problem 😕

**Comment by magnus-madsen** [comment]
If you don't mind spending more time, you could try to change this line:

https://github.com/flix/vscode-flix/blob/master/server/src/engine/flix.ts#L123

rebuild your vsix.

**Comment by magnus-madsen** [comment]
As for uncoded, the docs says:

"My aim is to provide a silent VSCode build that does not send telemetry, does not call home and does not do any unsolicited network connections."

Do you think its blocking our extension? We need to connect from VSCode to Flix (running as a Java process bound to a local port).

**Comment by dsv57** [comment]
Forget to mention, programs runs with Ctrl-Shift-P `Flix: run`, but not with Ctrl-F5: it opens dialog window "You do not have extension for debugging Flix. Should we find a Flix extension in the Maketplace?"

**Comment by magnus-madsen** [comment]
> Forget to mention, programs runs with Ctrl-Shift-P `Flix: run`, but not with Ctrl-F5: it opens dialog window "You do not have extension for debugging Flix. Should we find a Flix extension in the Maketplace?"

Thats separate. Thats just running the compiler in the terminal. Unfortunately even it that works it does not give you access to our neat IDE support. 

I would try without uncoded. Just to see.

**Comment by magnus-madsen** [comment]
> > Do you think its blocking our extension? We need to connect from VSCode to Flix (running as a Java process bound to a local port).
> 
> Of course, this was the first, what i thinked about. But no, author just run `sed` to replace domains with 0.0.0.0: https://gitlab.com/megastallman/uncoded/-/blob/main/build.sh?ref_type=heads

I see. So it should not matter. But it still _feels_ very suspicious because we are dealing with some connection issue where 127.0.0.1 fails and localhost works

**Comment by dsv57** [comment]
Heh, replaced `127.0.0.1` with `localhost` in `server/src/engine/flix.ts` and voilà: `Flix 0.50.0 Ready! (Extension: 1.31.0)`!

**Comment by magnus-madsen** [comment]
Does auto-complete work? E.g. if you type "main"?

**Comment by magnus-madsen** [comment]
Question is: What does it mean for the extension?

**Comment by dsv57** [comment]
Khm, not very, even after `:eval main()` (in the REPL). But it inserts all the `main()` with `tab` in the editor :)
![editor-autocomplete](https://github.com/user-attachments/assets/0b7fa1e7-6fa7-4b37-bdb2-d8e8a67ab656)
I s Also, Ctrl-F5 still offers to download Flix extension, so i need to use command `flix: run`.

**Comment by dsv57** [comment]
Oh, this nuance with autocompletion in the editor was beause of space in the funcion name.

> Question is: What does it mean for the extension?

I'm trying to figure it out. Obviously, it's more my OS fault.

**Comment by magnus-madsen** [comment]
Looks like the extension is working for now. Have fun with flix. We are on Gitter if you have questions about the language.

**Comment by dsv57** [comment]
First what comes to mind, is to use standard `"java.runtime.path"` setting when calling Flix, or to provide some local to extension java path setting. Because there is no convenient way to do this: https://stackoverflow.com/a/45637716

**Comment by dsv57** [comment]
I figured out, that it is due to my DNS resolver misconfiguration, although, replacing it with the default has not yet managed to fix the problem, that consists of inaccessibility of `localhost` server by `127.0.0.1` address. In reverse, everything works.

Can i help You with debugging autocompletion in the REPL or it is not yet implemented? And in the editor it works just as i written earlier — it pastes all the `main()` when i press `<tab>`...

Also, what should be done with the `<Ctrl-F5>` bug?
![run-without-debug](https://github.com/user-attachments/assets/5eaa21b4-e886-45f0-a426-5cb63387cfe7)

**Comment by magnus-madsen** [comment]
> Can i help You with debugging autocompletion in the REPL or it is not yet implemented? 

Not yet implemented. It uses two very different mechanism.

**Comment by magnus-madsen** [comment]
> Also, what should be done with the <Ctrl-F5> bug?

Its not a bug per se, I think its because we have not implemented that aspect yet, and we cannot just make VSCode run the program.

**Comment by dsv57** [comment]
Ok! I apologize for bothering you with my problem. I hope, that the ability to customize Java path or using standard setting will help other users. Thank You for so unusually nice language and support!

**Comment by magnus-madsen** [comment]
No worries. Have a good one!
