### ISSUE TITLE
Add Notifications for Main and Tests Completed/Failed

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#54]
I would like to add two notifications that simply state:

- Tests Passed (X/X)
- Tests Failed (X/Y)

I would also like a notification for main:

- "Main Finished"

**Comment by magnus-madsen** [comment]
The point is to aid the user in understanding what is happening since if you are "on the wrong output" you may see the spinner which then disappears with no more information.

**Comment by magnus-madsen** [comment]
I wonder of such a notification could be clickable to go to the right output?

**Comment by plougsgaard** [comment]
> I wonder of such a notification could be clickable to go to the right output?

You can add a button to a notification that could show the output. Just like the update notifications we have.

**Comment by magnus-madsen** [comment]
I think that would be nice. What do you think?

**Comment by plougsgaard** [comment]
It's a good idea. Let's do it.
