### ISSUE TITLE
Could not send message after 3 retries. Websocket not available

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#62]
On my Windows machine, when I open a Flix project I now just see:

Could not send message after 3 retries. Websocket not available.
Could not send message after 3 retries. Websocket not available.

**Comment by plougsgaard** [comment]
I just ran it getting the same results. Then I fully quit VSCode and ran it again and it worked fine. Could it be some faulty editor update that got patched?

**Comment by magnus-madsen** [comment]
I have seen it multiple times, but let me try to get confirmation.

**Comment by magnus-madsen** [comment]
This does seem to happen after standby

**Comment by magnus-madsen** [comment]
Would it be possible to:

(1) Show a notification saying that the connection has been lost and to restart Flix?
(2) Debounce this message so that it does not appear 3 or 100000 times?

**Comment by magnus-madsen** [comment]
Communication lost -> Do you want to restart?

(Ensure everything is cleared up)
