### ISSUE TITLE
Running a command while errors are present still causes a notification

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#65]
![image](https://user-images.githubusercontent.com/2287953/97698459-d4af0580-1aa8-11eb-8e7a-f44a41561c14.png)

**Comment by plougsgaard** [comment]
Just to be clear, you're talking about the "Running" notification, right?

**Comment by magnus-madsen** [comment]
Yes

**Comment by plougsgaard** [comment]
It will now show running for a short moment and then stop when errors are present. Not the most elegant solution, but quick.
