### ISSUE TITLE
Ensure that ./target is writable

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#83]
When the plugin starts it should:
- create `./target` if it does not exist.
- check that `./target` is writable if it exists.

If either operation fails, it should NOT start the Flix compiler, but instead report an error suggesting to the user that he should open the flix file in project in a writable dir.

**Comment by plougsgaard** [comment]
If not in a project folder, refuse to run providing an explanation.

**Comment by magnus-madsen** [comment]
> 
> 
> If not in a project folder, refuse to run providing an explanation.

Yes. This may be an orthogonal issue. Not sure.
