### ISSUE TITLE
Console.printLine not showing up

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#86]
A user reports:

Now ”Run Main” produces the result to standard output, but it doesn’t print the Console.printLine’s in the program.
They are printed in the standalone version in the shell (java -jar flix.jar)

**Comment by magnus-madsen** [comment]
Can be tested with: 

```
def main(): Int & Impure = Console.printLine("abc"); 0
```

**Comment by plougsgaard** [comment]
Fixed in 78de22816c372d882c74d512db624bc4f628d477.
